# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.entity.repository_calculate:
        class: Appbundle\Repository\CalcRepo
        fatory:
            - "@doctrine.orm.entity_manager"
            - getRepository
        arguments:
            - AppBundle\Entity\CalcEntity